name: cors_proxy
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0